# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["me@jakechampion.name"]
description = ""
language = "javascript"
manifest_version = 2
name = "gleam"
service_id = "zL7duUvlMvBHFYrmZfF2G0"

[scripts]
    build = "npm run build"
